# Generated by Django 4.1.7 on 2023-04-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('IdGame', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryId', models.IntegerField()),
                ('Name', models.CharField(max_length=500)),
                ('PathCoverGame', models.CharField(max_length=20000)),
                ('ReleaseDate', models.DateField()),
                ('CountNumberGame', models.IntegerField()),
                ('UrlPlayerRecord', models.CharField(max_length=20000)),
                ('IsDisabled', models.IntegerField()),
            ],
        ),
    ]
